# Configuration file example:  https://docs.astral.sh/ruff/configuration/
# All settings:                https://docs.astral.sh/ruff/settings/

fix = true
preview = true

line-length = 90
indent-width = 4

target-version = "py312"

include = [
    "src/ursus/**/*.py",
    "tests/**/*.py",
    "pyproject.toml",
]

exclude = [
    "src/ursus/_version.py",
    "src/ursus/infrastructure/persistence/migrations",
    "scripts",
]

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = false

[lint]
select = ["ALL"]

ignore = [
    "A003",
    "ANN401",
    "PLC2701",
    "EM101",
    "EM102",
    "CPY",
    "PLR6301",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "DOC201",
    "DOC202",
    "DOC402",
    "DOC501",
    "DOC502",
    "COM812",
    "PLR0917",
    "PLR0913",
    "EXE002",
    "TRY003",
    "S104",
]

[lint.per-file-ignores]
"tests/**/*.py" = [
    "S",
    "PLR0904",
    "PLR0914",
    "PLC1901",
    "RUF045",
    "RUF029",
    "PLR2004",
    "ARG001",
    "PLR0913",
    "FBT001",
    "RUF069",
    "PT011",
]

[lint.isort]
case-sensitive = true
combine-as-imports = true
force-wrap-aliases = true

[lint.pydocstyle]
convention = "google"
ignore-decorators = ["typing.overload"]

[lint.flake8-pytest-style]
fixture-parentheses = true
mark-parentheses = true
parametrize-names-type = "tuple"
parametrize-values-type = "tuple"
parametrize-values-row-type = "tuple"

[lint.flake8-type-checking]
runtime-evaluated-base-classes = ["ursus.infrastructure.persistence.base.Base"]
runtime-evaluated-decorators = ["dishka.provide", "dataclasses.dataclass"]
