package api

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
)

// AgentInstall returns a bash one-liner script for installing the agent on
// a remote host. Mirrors the legacy Python `/agent/install` endpoint.
//
// Usage from the host:
//   curl -fsSL http://<server>:8080/agent/install | sudo bash -s -- --key <KEY>
func (h *Handler) AgentInstall(c *gin.Context) {
	serverURL := serverBaseURL(c)
	script := buildInstallScript(serverURL)
	c.Data(http.StatusOK, "text/x-shellscript; charset=utf-8", []byte(script))
}

// AgentConfig returns a default config.yaml for the agent, ready to be saved
// on the host. Allows query params: ?server=...&key=...&id=...
func (h *Handler) AgentConfig(c *gin.Context) {
	server := c.DefaultQuery("server", serverBaseURL(c))
	key := c.DefaultQuery("key", "REPLACE_WITH_API_KEY")
	id := c.DefaultQuery("id", "agent-01")
	cfg := fmt.Sprintf(`# logvault agent — generated by logvault-go /agent/config
server_url: "%s"
agent_id:   "%s"
api_key:    "%s"

buffer:
  path: /var/lib/logvault-agent/buffer.db
  flush_interval_seconds: 5
  max_batch: 500

readers:
  - type: file
    paths:
      - /var/log/syslog
      - /var/log/auth.log
  - type: journald
    units: ["sshd", "nginx"]
`, server, id, key)
	c.Data(http.StatusOK, "application/yaml; charset=utf-8", []byte(cfg))
}

// AgentCompose returns a ready-to-use docker-compose.yml for the agent.
func (h *Handler) AgentCompose(c *gin.Context) {
	server := c.DefaultQuery("server", serverBaseURL(c))
	key := c.DefaultQuery("key", "REPLACE_WITH_API_KEY")
	id := c.DefaultQuery("id", "agent-01")
	compose := fmt.Sprintf(`version: "3.9"
services:
  logvault-agent:
    image: ghcr.io/ursus-siem/logvault-agent:latest
    container_name: logvault-agent
    restart: unless-stopped
    environment:
      SERVER_URL: "%s"
      API_KEY:    "%s"
      AGENT_ID:   "%s"
    volumes:
      - /var/log:/host/log:ro
      - /run/log/journal:/run/log/journal:ro
      - logvault-agent-buffer:/var/lib/logvault-agent
volumes:
  logvault-agent-buffer:
`, server, key, id)
	c.Data(http.StatusOK, "application/yaml; charset=utf-8", []byte(compose))
}

func serverBaseURL(c *gin.Context) string {
	scheme := "http"
	if c.Request.TLS != nil || strings.EqualFold(c.GetHeader("X-Forwarded-Proto"), "https") {
		scheme = "https"
	}
	host := c.Request.Host
	if h := c.GetHeader("X-Forwarded-Host"); h != "" {
		host = h
	}
	return scheme + "://" + host
}

func buildInstallScript(serverURL string) string {
	return `#!/usr/bin/env bash
# logvault-agent — automatic installer (generated by logvault-go).
set -euo pipefail

API_KEY=""
AGENT_ID="$(hostname)"
SERVER_URL="` + serverURL + `"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --key)    API_KEY="$2"; shift 2;;
    --id)     AGENT_ID="$2"; shift 2;;
    --server) SERVER_URL="$2"; shift 2;;
    *) echo "unknown arg: $1" >&2; exit 1;;
  esac
done

if [[ -z "$API_KEY" ]]; then
  echo "Usage: $0 --key <API_KEY> [--id <ID>] [--server <URL>]" >&2
  exit 1
fi

if ! command -v docker >/dev/null; then
  echo "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
fi

INSTALL_DIR="/opt/logvault-agent"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

echo "Fetching config & docker-compose from $SERVER_URL ..."
curl -fsSL "${SERVER_URL}/agent/config?id=${AGENT_ID}&key=${API_KEY}"   -o config.yaml
curl -fsSL "${SERVER_URL}/agent/compose?id=${AGENT_ID}&key=${API_KEY}"  -o docker-compose.yml

echo "Starting agent..."
docker compose up -d

echo "logvault-agent started. Logs: docker logs -f logvault-agent"
`
}
