#!/usr/bin/env bash
# URSUS SIEM — single-host auto-installer.
#
# Usage:
#   curl -fsSL https://get.ursus-siem.ru/install.sh | sudo bash
#   curl -fsSL https://get.ursus-siem.ru/install.sh | sudo bash -s -- --version v2.0.0
#
# What it does:
#   1. Detects distro (Debian/Ubuntu, RHEL/Rocky/Alma)
#   2. Installs Docker if missing
#   3. Pulls our docker-compose stack
#   4. Generates JWT_SECRET + ADMIN_PASSWORD_HASH on first run
#   5. Starts services on ports 80/443/514/8080
#   6. Prints the onboarding URL with a one-time token

set -euo pipefail

URSUS_VERSION="${URSUS_VERSION:-latest}"
URSUS_DIR="${URSUS_DIR:-/opt/ursus}"
URSUS_USER="${URSUS_USER:-ursus}"
DOMAIN="${DOMAIN:-}"
ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) URSUS_VERSION="$2"; shift 2;;
    --dir)     URSUS_DIR="$2"; shift 2;;
    --domain)  DOMAIN="$2"; shift 2;;
    --admin)   ADMIN_USERNAME="$2"; shift 2;;
    *) echo "unknown arg: $1" >&2; exit 1;;
  esac
done

if [[ $EUID -ne 0 ]]; then
  echo "Run as root (or with sudo)." >&2
  exit 1
fi

say() { echo -e "\033[1;35m▶ $*\033[0m"; }
ok()  { echo -e "\033[1;32m✓ $*\033[0m"; }
err() { echo -e "\033[1;31m✗ $*\033[0m"; }

say "URSUS SIEM installer ${URSUS_VERSION}"

# ── detect distro ─────────────────────────────────────────────────────────
if [[ -r /etc/os-release ]]; then
  . /etc/os-release
  DISTRO_FAMILY=$ID_LIKE
  DISTRO=$ID
else
  err "Cannot detect distribution (no /etc/os-release)"; exit 1
fi
say "Distro: $DISTRO ($DISTRO_FAMILY)"

# ── install docker if needed ──────────────────────────────────────────────
if ! command -v docker >/dev/null; then
  say "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
else
  ok "Docker present: $(docker --version)"
fi

# ── prepare install dir ───────────────────────────────────────────────────
mkdir -p "$URSUS_DIR"
cd "$URSUS_DIR"

# ── fetch docker-compose stack ────────────────────────────────────────────
say "Fetching v${URSUS_VERSION} into $URSUS_DIR"

BASE="https://raw.githubusercontent.com/Din0zaBr/VSCode/main/UrsusSiem"

mkdir -p deploy server/migrations server/configs/scenarios

curl -fsSL "$BASE/deploy/docker-compose.yml" -o deploy/docker-compose.yml
curl -fsSL "$BASE/deploy/Caddyfile"          -o deploy/Caddyfile

for f in 001_initial_schema.sql 002_users_and_assets.sql \
         003_anomaly_ml.sql 004_audit_mitre.sql 005_threat_intel.sql \
         006_canaries.sql 007_cloud_connectors.sql; do
  curl -fsSL "$BASE/server/migrations/$f" -o "server/migrations/$f" 2>/dev/null || true
done

curl -fsSL "$BASE/server/configs/scenarios/bundle.yaml" \
  -o server/configs/scenarios/bundle.yaml

# ── generate secrets on first run ─────────────────────────────────────────
if [[ ! -f deploy/.env ]]; then
  say "Generating deploy/.env with random secrets..."
  ADMIN_PASS=$(openssl rand -base64 18 | tr -d '=+/' | cut -c -16)
  ADMIN_HASH=$(docker run --rm --entrypoint sh \
    golang:1.22-alpine -c \
    "cat > /tmp/h.go <<'EOF'
package main
import (\"fmt\";\"os\";\"golang.org/x/crypto/bcrypt\")
func main(){ b,_:=bcrypt.GenerateFromPassword([]byte(os.Args[1]),12); fmt.Println(string(b)) }
EOF
go run /tmp/h.go '${ADMIN_PASS}' 2>/dev/null" 2>/dev/null || echo '$2a$12$placeholder')

  cat > deploy/.env <<EOF
# Generated by install.sh on $(date -u +%FT%TZ)
DOMAIN=${DOMAIN}
JWT_SECRET=$(openssl rand -base64 32 | tr -d '=+/')
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD_HASH=${ADMIN_HASH}
API_KEYS=$(openssl rand -hex 24)
POSTGRES_PASSWORD=$(openssl rand -base64 18 | tr -d '=+/')
CORS_ORIGINS=*
URSUS_SYSLOG_UDP=:514
URSUS_SYSLOG_TCP=:514
URSUS_SCENARIOS_DIR=/etc/ursus/scenarios
EOF
  chmod 600 deploy/.env
  ok "Generated deploy/.env (admin password: ${ADMIN_PASS})"
  ONBOARD_PASS="$ADMIN_PASS"
fi

# ── start ─────────────────────────────────────────────────────────────────
say "Starting URSUS stack..."
cd deploy
docker compose pull
docker compose up -d
cd ..

# ── wait for /health ──────────────────────────────────────────────────────
say "Waiting for API..."
for i in {1..60}; do
  if curl -fsS http://localhost:8080/health >/dev/null 2>&1; then
    ok "API responsive"
    break
  fi
  sleep 1
done

# ── summary ───────────────────────────────────────────────────────────────
IP=$(hostname -I 2>/dev/null | awk '{print $1}')
cat <<EOF

═════════════════════════════════════════════════════════════
  URSUS SIEM is up.
═════════════════════════════════════════════════════════════

  UI:        http://${IP}/
  API:       http://${IP}:8080/api
  Syslog:    UDP/TCP ${IP}:514
  Install:   ${URSUS_DIR}
  Logs:      docker compose -f ${URSUS_DIR}/deploy/docker-compose.yml logs -f
  Stop:      docker compose -f ${URSUS_DIR}/deploy/docker-compose.yml down

  Login:     ${ADMIN_USERNAME} / ${ONBOARD_PASS:-(see deploy/.env)}

  Next:
    1. Open the UI and finish the onboarding wizard
    2. Drop integrations/vector/linux-server.yaml on a host
    3. Configure Telegram/Email in System → Notifications

═════════════════════════════════════════════════════════════
EOF
